stages:
  - build
  - deploy

build:
  image: node:10
  stage: build
  services:
    - mongo:latest
  script:
    - npm install

deploy_production:
  image: google/cloud-sdk:alpine
  stage: deploy
  environment: Production
  only:
  - master
  script:
  - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml

after_script:
- rm /tmp/$CI_PIPELINE_ID.json